### PR TITLE
Add Elm

### PR DESCRIPTION
**Pull request by kolybasov**
There is FizzBuzz for [Elm](http://elm-lang.org). You can check result at http://elm-lang.org/try

### CODE REVIEW

**Comment by nloveladyallen** [comment]
Convention for this repo is to use lowercase for the filename. 

Also, 6k sloc output seems a bit excessive for FizzBuzz… Is there any way to make it shorter?

**Comment by kolybasov** [comment]
@nloveladyallen I will rename, sorry but didn't found convention. But what you mean about 6k sloc? I can change it to this one maybe:

```elm
import Html exposing (Html, div, text)


fizzbuzz : Int -> Html a
fizzbuzz n =
    case ( n % 3, n % 5 ) of
        ( 0, 0 ) ->
            text "FizzBuzz"

        ( 0, _ ) ->
            text "Fizz"

        ( _, 0 ) ->
            text "Buzz"

        _ ->
            text (toString n)


main : Html a
main =
    div [] <|
        List.map (\n -> div [] [ fizzbuzz n ]) [1..100]
```

**Comment by nloveladyallen** [comment]
@kolybasov sloc = "significant lines of code" (non-blank, non-comment lines)

I'm referring to the HTML output, not the Elm code.

**Comment by kolybasov** [comment]
@nloveladyallen actual output of the code itself is 101 div with numbers and Fizz/Buzz. But if you talking about `elm-make elm.elm --output=index.html && cat index.html | wc -l` it's kinda different. Because elm-make compile not only your code, but dependencies as well:

```bash
~/Downloads ❯❯❯ elm-make elm.elm --output=index.html                                                                                                          ⏎
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 4.0.5
    elm-lang/html 1.1.0
    elm-lang/virtual-dom 1.1.1

Do you approve of this plan? [Y/n]
Starting downloads...

  ● elm-lang/virtual-dom 1.1.1
  ● elm-lang/html 1.1.0

● elm-lang/core 4.0.5
Packages configured successfully!
Success! Compiled 31 modules.
Successfully generated index.html
```

So it makes more sense to check only Elm code, not compiled output.

**Comment by zenware** [comment]
Is that collection mapping on selection?

**Comment by zenware** [comment]
I do think it makes the most sense to refer to the Elm code and not it's compiled output. We don't really consider the compiled output of a C program as the relevant portion, as long as it's actually functional.

**Comment by zenware** [comment]
Thanks 👍

**Pull request merged**
