### PR TITLE
Add Crystal

### PR DESCRIPTION
**Pull request by yous**
See http://crystal-lang.org/.

### CODE REVIEW

**Comment by nloveladyallen** [comment]
Crystal syntax is basically Ruby. Just replace the single quotes with double quotes in the Ruby version and it'll work with Crystal, no need for a separate version.

**Comment by yous** [comment]
Hmm... Should we remove `python2.py` and `python3.py` in favor of `python.py`, then?

**Comment by zenware** [comment]
I think there could be a python version compatible with both 2 and 3

**Comment by zenware** [comment]
Also, I think if we are going to disregard this in favor of only having the ruby version, that we should figure out a way to annotate all the language compilers/interpreters that can correctly parse a particular file.

Otherwise, I'm merging the request for now, because the idea (my original idea for this repo) is to be a quick reference for syntax. Something more useful for glancing and going than 'hello-world', but not something that takes more than a few minutes to read or figure out.

**Comment by zenware** [comment]
Symlinked

**Pull request merged**
