### PR TITLE
Commodore BASIC

### PR DESCRIPTION
**Pull request by elliotwutingfeng**
Commodore BASIC

### CODE REVIEW

**Comment by nloveladyallen** [comment]
Gives a syntax error when using [this interpreter](https://github.com/mist64/cbmbasic)

**Comment by elliotwutingfeng** [comment]
Could you try this on your interpreter? The original code was tested on the VICE C64 Emulator (which accepted only lowercase letters when pasting-in code).

```basic
100 FOR X = 1 TO 100
110 FLAG=1
120 IF NOT (X-INT(X/3)*3)=0 THEN 150
130 FLAG=0
140 PRINT "FIZZ";
150 IF NOT (X-INT(X/5)*5)=0 THEN 180
160 FLAG=0
170 PRINT "BUZZ";
180 IF FLAG=1 THEN PRINT X;
190 PRINT
200 NEXT X
RUN
```

**Comment by nloveladyallen** [comment]
That works. The fact that one system only accepts lowercase and another only accepts uppercase presents a bit of an issue, but I'm inclined to use the uppercase since it's how the characters would've appeared on the original hardware.

**Comment by elliotwutingfeng** [comment]
Alright, it has been set to uppercase.

**Pull request merged**
