### PR TITLE
Add Eiffel implementation

### PR DESCRIPTION
**Pull request by BitPatty**

### CODE REVIEW

**Comment by zenware** [comment]
What do you use to run this code?

**Comment by zenware** [comment]
In order to try and get it working, I've downloaded and installed [Eiffel Studio](https://sourceforge.net/projects/eiffelstudio/) and I encountered an issue when trying to build the code related to C/C++ Compilation of base-scoop-safe

"eiffel user files\19.05\precomp\spec\win64\EIFGENs\base-scoop-safe\W_code/mingw/precomp.lib: No such file or directory"

Trying to research how to solve this and I'll put my notes here.

**Comment by BitPatty** [comment]
Try to either run the precompilation wizard under 'Tools' or to disable precompilation (Project > Project Settings > Groups > Precompiles)

**Comment by zenware** [comment]
@BitPatty seems like with your suggestion I've got it compiling and executing, but for some reason, I don't see any console output? Does Eiffel produce some binary artifact somewhere like a PE file?

**Comment by BitPatty** [comment]
Click Compile to make sure the compilation works & then Run. It should show you you the output window on top of the IDE:

s1

p2

**Comment by zenware** [comment]
Got it, thanks :)

**Pull request merged**
