### PR TITLE
Added LOLCODE 1.2 implementation

### PR DESCRIPTION
**Pull request by mikasjp**
[LOLCODE official homepage](http://lolcode.org/)
[LOLCODE on Esolang Wiki](https://esolangs.org/wiki/LOLCODE)

You can check my code [HERE](https://repl.it/languages/lolcode)

### CODE REVIEW

**Comment by mikasjp** [comment]
@zenware, what do You think about it?

**Comment by nloveladyallen** [comment]
The program seems to start at 0 (first line of output is `FizzBuzz`, then `1` etc.) despite `FIZZBUZZVAR` being set to `1`. Not sure why.

**Comment by mikasjp** [comment]
I tested the code [here](https://repl.it/repls/TidyTanUmbrellabird) and the output seems to be okay. I also checked the output using diff.

**Comment by nloveladyallen** [comment]
According to [the spec](https://github.com/justinmeza/lolcode-spec/blob/master/v1.2/lolcode-spec-v1.2.md), it shouldn't work. For-loop indices must be local to the loop, and can only start from 0, so a for-loop wouldn't work for FizzBuzz. Therefore, you would want to do a while-loop:

    I HAS A FIZZBUZZVAR ITZ 1
    IM IN YR FIZZBUZZLOOP
        BTW logic
        BOTH SAEM FIZZBUZZVAR AN 100, O RLY?
        YA RLY
            GTFO
        OIC
        FIZZBUZZVAR R SUM OF FIZZBUZZVAR AN 1
    IM OUTTA YR FIZZBUZZLOOP

**Comment by mikasjp** [comment]
How about this solution @nloveladyallen?

**Comment by zenware** [comment]
I like it.

**Comment by mikasjp** [comment]
So @zenware ? Would You merge it?

**Comment by zenware** [comment]
@mikasjp Thanks :)

**Pull request merged**
