### PR TITLE
FizzBuzz in Assembly

### PR DESCRIPTION
**Pull request by sunnypatel165**
_Reviewer: Is this modular enough?
Me: 😨 
Reviewer: Oh S#!1 this is assembly!_

### CODE REVIEW

**Comment by Rayzr522** [comment]
Owwwwww...... MY BRAIN

**Comment by nloveladyallen** [comment]
"assembly" is a big vague. The filename shoud probably specify that it's for nasm. 

Currently on my phone, can you verify this ouputs the same as the contents of text.txt ? Pipe to `diff - text.txt` as a shortcut.

**Comment by zenware** [comment]
IIRC NASM supports 8088 Intel ASM?

**Comment by sunnypatel165** [comment]
@zenware I think it does! 
Here's the code in [action](http://ideone.com/dYCdPR)
And thanks, also let me know or feel free to change the file name as suggested above!

**Comment by nloveladyallen** [comment]
Output was incorrect ("Fizz Buzz" instead of "FizzBuzz"), fixed with 2768be4

**Comment by zenware** [comment]
@nloveladyallen Thanks for keeping on top of it!

**Pull request merged**
