### PR TITLE
Create rust.rs

### PR DESCRIPTION
**Pull request by nloveladyallen**
> Rust is a general-purpose, multi-paradigm, compiled programming language sponsored by Mozilla Research. It is designed to be a "safe, concurrent, practical language", supporting pure-functional, imperative-procedural, and object-oriented styles.

### CODE REVIEW

**Comment by zenware** [comment]
I wonder if these quoted comments you're using as a PR description might be better as a comment at the top of each file..

**Comment by zenware** [comment]
The primitive type you specified i32 doesn't actually need to be signed because it's always positive so it can be u32, and it also doesn't need 2^32-1 possible values... u8 will suffice.

**Comment by nloveladyallen** [comment]
Fixed. I just looked up enough about Rust to get it working, also I generally use scripting languages and don't worry about integer size or signed/unsigned.

**Comment by zenware** [comment]
@nloveladyallen It's only like.. one of the most important things.
Rust does have a generic "num" type, which is not a primitive type and would automatically handle optimization, as would the type inference, but I'd prefer type hinting if it's available

**Pull request merged**
