### PR TITLE
Add clojure implementation.

### PR DESCRIPTION
**Pull request by sergey-lagutin**

### CODE REVIEW

**Comment by sergey-lagutin** [comment]
It's a non-public definition.

**Comment by zenware** [comment]
Wow, I'm also very attentive, so by non-public, does that mean 'private' or does that mean 'protected' as in, is there a way to access it at the very least from a child, or can you somehow force it to crack open a different way?

**Comment by nloveladyallen** [comment]
@zenware http://christophermaier.name/blog/2011/04/30/not-so-private-clojure-functions

**Comment by zenware** [comment]
@nloveladyallen Thank you for furthering my learning :)

**Pull request merged**
