### PR TITLE
Create R.R

### PR DESCRIPTION
**Pull request by project-delphi**
This is good implementation of fizzbuzz in the R style

### CODE REVIEW

**Comment by nloveladyallen** [comment]
To maintain consistency with other file names in this repo and R conventions, this should be named r.R.

**Comment by zenware** [comment]
@nloveladyallen I agree there should be some consistency, but the filenames aren't truly standardized.
Although, @project-delphi seems to be pretty new to Github if not to git, and I think learning how to update a pull request with more commits will be more valuable for them than just me merging and fixing this would be for the project.

**Comment by project-delphi** [comment]
Thanks. Change made.

**Comment by zenware** [comment]
@project-delphi Writing some prose about the actual changes you made is much nicer than just writing "updated x file", which communicates pretty much no information about the actual change. And makes the `git log` command virtually useless. I don't really care about polluted history, and rewriting public history is the worst, so I'm going to accept it. 

You should investigate how to rebase and squash your local history before pushing something like that though. And if you don't already practice meaningful commit messages in other projects I think that's a good idea as well.

This is a good read http://chris.beams.io/posts/git-commit/

Cheers!

**Comment by project-delphi** [comment]
Cheers!

**Pull request merged**
