### PR TITLE
Create sed.sh

### PR DESCRIPTION
**Pull request by mydzor**
FizzBuzz in sed

### CODE REVIEW

**Comment by nloveladyallen** [comment]
Doesn't work.

    sed: 1: "3~3s/.*/Fizz/;5~5s/[0-9 ...": invalid command code ~

**Comment by mydzor** [comment]
works fine with "sed (GNU sed) 4.2.2"
which version of sed are you using?

**Comment by nloveladyallen** [comment]
Same version.

**Comment by mydzor** [comment]
It looks like your sed does not have GNU extensions, the error you have is complaining about "~" command, which according to man page is valid in GNU sed:

> addr1,~N
>     Will match addr1 and the lines following addr1 until the next line whose input line number is a multiple of N. 

I will try to think about how to do this using only posix commands

**Comment by mydzor** [comment]
@nloveladyallen Can you check if the new version works for you?

**Comment by nloveladyallen** [comment]
This works. Not sure why my sed doesn't have GNU extensions though.

**Comment by zenware** [comment]
Cool!

**Pull request merged**
