### PR TITLE
J implementation

### PR DESCRIPTION
**Pull request by alpha123**
There are a lot of ways to do this in J and I can't claim to be an expert, but it's fairly clean and works.

### CODE REVIEW

**Comment by zenware** [comment]
Whoa, this is one of those golf langs. Neat! If you get a chance it would be cool if you could explain it to me
Also, I tried to run it [here](https://joebo.github.io/j-emscripten/) and couldn't get it working. I'll build a local version later and see if that helps

**Comment by nloveladyallen** [comment]
It works fine on my local version (I downloaded a precompiled binary), but it doesn't seem to work on that web version. A bug in the website, probably.

**Comment by alpha123** [comment]
Believe it or not, it's actually more than just for golfing and is a real, practical language. J is descended from APL and K, which are heavily used in the financial industry to this day. Chances are if you've cashed a check, you've used an APL system. (APL is very similar to J, but not limited to ASCII characters....)

As for how it works, you read J and similar languages right-to-left:

    >:i.100

`i.` is iota, which generates an array [0,100). `>:` is increment, so we have [1,100].

    (('Fizz'#~0=3&|),'Buzz'#~0=5&|))

This is parenthesized, which overrides the usual right-to-left no-precedence parsing. It applies two verbs (functions) to the array from above. This is how we get 'Fizz', 'Buzz', or 'FizzBuzz':

    'Fizz'#~0=3&|

`3&|` is modulo 3—the `|` verb is modulo and the `&` modifier binds it to 3, creating a new verb. `0=` is just equality check for 0, and returns 1 or 0. `#~` is the element-wise repeat operator, so `'Fizz' #~ 1` is `'Fizz'` and `'Fizz' #~ 0` is `''`. (`'Fizz' #~ 2` is `'FFiizzzz'`.)

All in all, `(('Fizz'#~0=3&|),'Buzz'#~0=5&|))` gets us the core Fizz/Buzz/FizzBuzz logic. `0"` forces rank 0 (scalar) context on the verb to the left, and applies its right argument. I'm not familiar enough with J to elaborate on the exact significance of this....

`(":[^:(''-:])` now gets passed an array of [1,100] as well as an array of fizzbuzzes, and picks its left argument if the right is the empty string and the right otherwise. That's how you get the numbers in between.

Phew. As an amateur J-er myself, I may have learned more from explaining that than I actually managed to explain to you....

**Comment by zenware** [comment]
@alpha123 Thanks, and apparently.. you're welcome 👍 
`>: ` is _pre increment_, is there a post increment? and if so, would it be `:>` ?
I'm also now very interested in the significance of `0"`, I'm sure there are some contexts in which it carries heavy implementations. 😄

**Pull request merged**
