### PR TITLE
Created Fizz Buzz in the beta language

### PR DESCRIPTION
**Pull request by peterhull90**
BETA was a object-oriented language in the SIMULA family, developed from 1975 to the 1990's in Norway.
See [HOPL](http://hopl.info/showlanguage.prx?exp=1032&language=BETA).

### CODE REVIEW

**Comment by nloveladyallen** [comment]
I've looked into BETA a bit and tried to install the compiler with no success. Can you confirm this gives exactly the correct output? Specifically, looking at the source, it may start at 0 instead of 1.

**Comment by peterhull90** [comment]
I can confirm the output starts like this:
```
[peter@localhost peter]$ ./fizzbuzz |head
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
```

My reference is OBJECT-ORIENTED PROGRAMMING IN THE BETA PROGRAMMING LANGUAGE by O L Madsen, specifically section 5.2:

> 5.2 For-imperative
> The iteration control structure of BETA is called a for-imperative and has the following form:
> `(for Index: Range repeat Imperative-list for)`
> where `Index` is the name of an integer-object and `Range` is an integer evaluation. `Range` is evaluated prior to the execution of the for-imperative, and determines the number of times that `Imperative-list` is executed. `Index` will step through the values `[1, 2, ..., Range]`.

**Comment by peterhull90** [comment]
Regarding the compiler I have got a very old version of Redhat (9, Shrike) running in a VM - this is old enough to run the last release of Mjolner BETA. I find it an intriguing language and I was trying to get some of the Rosetta code examples written in Beta, when I saw a link to the 'hello-world' project and from there to your repository.

**Comment by peterhull90** [comment]
I woke up in the night realising this code wasn't correct :fearful: I have amended the commit accordingly.

**Comment by zenware** [comment]
@peterhull90 I've had a couple of those nights freak me out pretty bad.
Thanks for the contribution!

**Pull request merged**
